// <auto-generated />
namespace FSIX.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FluentConfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FluentConfig));
        
        string IMigrationMetadata.Id
        {
            get { return "201308141704585_FluentConfig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
