// <auto-generated />
namespace FSIX.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LinkLogEntriesToUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkLogEntriesToUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201308142258464_LinkLogEntriesToUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
